### ISSUE TITLE
Remember previous choices in the interactive installer

### ISSUE THREAD

**Issue by bashrc** [bashrc/freedombone#43]
So if you quit from the installer half way through when you start again it should remember previous choices or begin from where you left off.

**Comment by bashrc** [comment]
Mostly done, apart from radiolist items

**Comment by jreeve0805** [comment]
Very nice feature thanks.

**Comment by bashrc** [comment]
The radiolist items seem difficult to alter based upon the existing config file, without producing a lot of copy-and-pasted code. Maybe there's a better way.
