### ISSUE TITLE
Fix tripwire

### ISSUE THREAD

**Issue by bashrc** [bashrc/freedombone#45]
Not sure that it's working as intended

**Comment by ikmaak** [comment]
Tripwire install starts, and has a lot of errors, before giving up and segfaulting. This ends the script, and declares success, although there is some part that is not executed.
There is only a Debian "It Works" page on all domains, while the owncloud/main domain pushes to a blank /doku.php page.

Partial error message:
### Filename: /proc/15130/wchan
### No such file or directory
### Continuing...
Software interrupt forced exit: Segmentation Fault
Segmentation fault

  *** Freedombone installation is complete. Rebooting... ***

See /home/alias/README for post-installation instructions.

**Comment by jreeve0805** [comment]
ikmaak you are seeing the same behavior I am seeing, but I don't remember there being a problem with tripwire on my installation, however the end result is the same. The Debian "It Works" page is all I get from the wiki page. I confirmed that Apache2 was removed on my system but the Debian "It Works" page was not cleaned up. 

Here is what I am seeing. 
![screenshot from 2015-02-08 20 45 03](https://cloud.githubusercontent.com/assets/10797116/6100049/a44a0a6e-afd5-11e4-9fac-6af711e3572d.png)

**Comment by jreeve0805** [comment]
I fixed my wiki page. see post #49

**Comment by bashrc** [comment]
On the Apache problem that should now be fixed. It was installed by default as part of Owncloud, so now after the Owncloud installation Apache is uninstalled and /etc/apache2 is deleted. I think that should eliminate any Apache messages like the above.

**Comment by bashrc** [comment]
Tripwire now no longer reports changes to /proc or /var/log, so should work as expected with a daily report.
