### ISSUE TITLE
freedombone menuconfig (mailbox only install)

### ISSUE THREAD

**Issue by jreeve0805** [bashrc/freedombone#48]
When installing via: freedombone menuconfig and choosing the option "mailbox only", the installation works for a while and then fails right after configuring nginx, and php witih error:

"No Owncloud domain name was specified".

**Comment by bashrc** [comment]
This must be a bug, because for the mailbox only install that's all it should do. It shouldn't install a web server or Owncloud.

**Comment by bashrc** [comment]
This was indeed a bug.  It is fixed by: https://github.com/bashrc/freedombone/commit/a99aaab878ae39c65dd948ec2c73cba00d7c5281

On the Beaglebone during the second stage of installation the system type was not being read and so defaulted to "full".
