### ISSUE TITLE
Device name for MicroSD Card

### ISSUE THREAD

**Issue by MarcusMoeller** [bashrc/freedombone#56]
I wanted to write the MicroSD card using the slot in my Lenovo Notebook. The device itself creates a node like /dev/mmcblk0 - the first partition would be /dev/mmcblk0p1

fredombone-prep -d /dev/mmcblk0 would lead to an error like:

The microSD drive could not be found at /dev/mmcblk01

**Comment by bashrc** [comment]
Ah, I think this is a limitation of the way I've done things thus far, which was based around /dev/sdX. Whether it's sdX or mmcblkXpY depends on whether it's a USB or SDcard interface.

I think I can make a workaround for this.

**Comment by MarcusMoeller** [comment]
The device itself is named /dev/mmcblk0, but the partition is named /dev/mmcblk0p1 (for first partition, note the p1). So if I execute fredombone-prep -d /dev/mmcblk0 it still leads to an error like:

The microSD drive could not be found at /dev/mmcblk01

as it would expect  /dev/mmcblk0p1 (with the p), instead.

**Comment by bashrc** [comment]
Although I don't have a system to test on I think d301ebf72b5345b77ea104b0be31722680032491 should fix that.

**Comment by MarcusMoeller** [comment]
Yes, this works. Thanks for taking care.
