### ISSUE TITLE
Where else do I switch out the Debian File to make the freedombone-prep command work? 

### ISSUE THREAD

**Issue by flixi** [bashrc/freedombone#60]
https://github.com/bashrc/freedombone/blob/master/src/freedombone-prep#L55

I get an error that the firmware can't find the version of the file and a manual search shows that this file is wrong and doesn't exist anymore.

**Comment by bashrc** [comment]
I'm in the process of fixing this by moving to using vmdebootstrap to generate an image from scratch, rather than relying upon a pre-made image.

**Comment by flixi** [comment]
Great, is there a hotfix?

**Comment by bashrc** [comment]
I'm deprecating the prep command and am going to update the documentation to use the new image command. Once you have an image you can then just dd it to a microSD or run it in qemu or virtualbox.

**Comment by bashrc** [comment]
New build instructions: http://freedombone.uk.to/installation.html

**Comment by flixi** [comment]
Works now. Thanks.
