### ISSUE TITLE
Translation strings should be in json-Format

### ISSUE THREAD

**Issue by flixi** [bashrc/freedombone#61]
It makes it possible to translate hem using transifex, which is a powerful and easy to use translation tool, even though it's not that easy to set up it's going to make translating stuff that much easier.
And also try to get this file to be in one json file. ;)
https://github.com/bashrc/freedombone/commit/15c9d3868e8db7e92f03ae4641bf0af7e6f29530

**Comment by bashrc** [comment]
Maybe something like this. It would also need to do the reverse conversion.

https://github.com/mikeedwards/po2json
