### ISSUE TITLE
Change license to AGPLv3+

### ISSUE THREAD

**Issue by pizzamaker** [bashrc/freedombone#63]
Affero further protects the project against SaaSS :)

**Comment by bashrc** [comment]
Since this is primarily about network services AGPL might be a better license. However, I notice that Freedombox is also under GPL3 and I'm inclined to think that they know better what type of license is most appropriate for this sort of system.

**Comment by bashrc** [comment]
But it looks like the Freedombox Plinth UI is under AGPL. I'll have to read more about AGPL. Presumably it's mainly to stop what Google does - supplying services based on modifications to free software but not making their changes available.

**Comment by pizzamaker** [comment]
Cool! Probably best to state AGPLv3 "or later", to solve any potential issues with forward compatibility.

**Comment by bashrc** [comment]
Ok, will do that.
