### ISSUE TITLE
freedombone install on 'laptop'

### ISSUE THREAD

**Issue by jreeve0805** [bashrc/freedombone#64]
I run "freedombone menuconfig", and get an error:
configure: error: *** SSL Library (GnuTLS) not found!

As a result I tried:  "apt-get install gnutls-bin", it complained about its dependencies for libopts25, so I manually installed that with dpkg. 

Even after that I still get the same error: 
configure: error: *** SSL Library (GnuTLS) not found!

======== Freedombone.cfg ========   Replaced sensitive data with *****
MY_USERNAME=*****
DEFAULT_DOMAIN_NAME=*****
DEFAULT_DOMAIN_CODE=*****
SYSTEM_TYPE=mailbox
INSTALLING_ON_BBB=no
USB_DRIVE=/dev/sdb1
DDNS_PROVIDER=default@freedns.afraid.org
DDNS_USERNAME=*****
DDNS_PASSWORD=*****
DEFAULT_LANGUAGE=en_GB.UTF-8
MY_NAME=*****
MY_EMAIL_ADDRESS=*****@*****.ca
DEBIAN_REPO=ftp.de.debian.org
NAMESERVER1=85.214.73.63
NAMESERVER2=213.73.91.35
ENABLE_SOCIAL_KEY_MANAGEMENT=yes
ESSID=mesh
BATMAN_CELLID=any
ONION_ONLY=no
FRIENDS_MIRRORS_SSH_PORT=2222

**Comment by bashrc** [comment]
Presumably this error came up some way through the install. It might be that one of the applications depends on GnuTLS (ngirc maybe). For generating certificates, dhparams and such only openssl is used.

Are you installing on debian 8.x, and if so was it a new installation of was there some pre-existing stuff on there?

**Comment by bashrc** [comment]
Also is the architecture 32 or 64bit? ARM or x86? It might be that there's some broken package on a particular architecture.

**Comment by bashrc** [comment]
Also sometimes the particular debian repo is unreliable. The default is ftp.us.debian.org, but you can set it to other things.

    echo "DEBIAN_REPO=ftp.de.debian.org" >> freedombone.cfg
    freedombone -c freedombone.cfg

**Comment by jreeve0805** [comment]
This is a fresh 8.3 install. I did not install a GUI, printer support, or ssh. The architecture is x86-64. It looks like I am using a germn repo. I will change it to the USA and see if that helps.

**Comment by jreeve0805** [comment]
I tried again with another fresh installation. This time I choose the GUI options, and I set my repo to ftp.us.debian.org. Then I ran freedomebone -c ../freedombone.cfg

Here is the output and error message:


root@mailbox:/home/postmaster/freedombone/src# freedombone -c ../freedombone.cfg 
System type: mailbox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package automake1.11
E: Couldn't find any package by regex 'automake1.11'
fatal: destination path '/root/build/inadyn' already exists and is not an empty directory.
warning: refname 'fadbe17f520d337dfb8d69ee4bf1fcaa23fce0d6' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex. These refs
may be created by mistake. For example,

  git checkout -b $br $(git rev-parse ...)

where "$br" is somehow empty and a 40-hex ref is created. Please
examine these refs and maybe delete them. Turn this message off by
running "git config advice.objectNameWarning false"
fatal: A branch named 'fadbe17f520d337dfb8d69ee4bf1fcaa23fce0d6' already exists.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for ANSI C header files... (cached) yes
checking for arpa/inet.h... yes
checking for arpa/nameser.h... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for sys/ioctl.h... yes
checking for sys/socket.h... yes
checking for sys/types.h... (cached) yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for gnutls_init in -lgnutls... no
configure: error: *** SSL library (GnuTLS) not found!
root@mailbox:/home/postmaster/freedombone/src#

**Comment by jreeve0805** [comment]
I added the repos below (to get my gpu working), low and behold, I ran freedombone again and got past the GnuTLS error. 

# Debian 8 "Jessie"
deb http://httpredir.debian.org/debian/ jessie main contrib non-free

**Comment by bashrc** [comment]
I also have jessie-updates and jessie-backports in /etc/apt/sources.list

Instead of just removing non-free I think sources.list should maybe be generated during install to ensure that it's always consistent.

The problem here looks like not finding the package for automake1.11 https://packages.debian.org/jessie/automake1.11 which is needed for the inadyn build. GnuTLS is on the same apt-get line and so that's why it also didn't install. I should add more checking for these kinds of failures.

**Comment by bashrc** [comment]
So I've added a few commits which should increase the reliability of the install, but in this case it's most likely that automake1.11 was just temporarily inaccessible from ftp.de.debian.org. I've noticed this kind of thing also occurring when httpredir is used to automatically select a debian mirror, and the solution is typically to just run the install again.
