### ISSUE TITLE
Tor not found when updating ssh

### ISSUE THREAD

**Issue by jreeve0805** [bashrc/freedombone#65]
root@mailbox:/home/postmaster/freedombone/src# freedombone -c ../freedombone.cfg 
System type: mailbox
Tor not found when updating ssh

ran apt-get install tor, manually to proceed,

**Comment by bashrc** [comment]
Ok. Might need to install tor at an earlier stage in the sequence.

**Comment by bashrc** [comment]
It looks like tor is installed at a suitably early stage, but that there was no check that the package install was successful. I've added a commit to do that.

https://github.com/bashrc/freedombone/commit/f2157d3e067a5178aabb3f811b5b0e0aeab5c7a8
