### ISSUE TITLE
Question: .onion addresses with mesh variant

### ISSUE THREAD

**Issue by deavmi** [bashrc/freedombone#66]
Why is this true. Surely you can have the device have an interface on the Internet and one on the mesh and therefore by being on the Internet support `.onion` addresses?

> Except for the mesh variant all web systems installed also have an equivalent onion address so that they may be accessed via a Tor browser.

**Comment by bashrc** [comment]
There could be a mesh to internet bridge, and Tor might work in that case, but as far as I know Tor is fundamentally a client/server system designed for the internet, so it either wouldn't work on a mesh or would work very badly. Anything which changes mesh routing is likely to result in bad performance.
