### ISSUE TITLE
Odroid C1+

### ISSUE THREAD

**Issue by cron410** [bashrc/freedombone#67]
I couldn't find direct mention of this board in your documentation, so just wanted to let you know I have one we can test with. Spare SD card to write images to and all that.

**Comment by bashrc** [comment]
The best way to use an Odroid would be to set Debain jessie up on it, then install with:

    sudo apt-get install git
    git clone https://github.com/bashrc/freedombone
    cd freedombone
    git checkout stockholm
    sudo make install
    freedombone

The Odroids aren't supported by the image builder, since they require a closed blob to boot.

**Comment by jeroen7s** [comment]
do you need to use debian jessie, or can we use Ubuntu instead? or will using ubuntu cause issues?
not that i have anything against using debian jessie, just have a lot more experience using Ubuntu

so the best way would be to use Raspbian on it?

**Comment by jeroen7s** [comment]
also should we use the stockholm branch as being relatively stable?
don't really know what would stand for being "stable" or the latest release version or whatever

**Comment by bashrc** [comment]
The stockholm branch is old now. Use the stretch branch instead.

You should be running Debian stretch, and there is usually a stretch version of Armbian available.

**Comment by jeroen7s** [comment]
seems like the latest "stable" armbian for my device (odroid HC1) is still jessie
there's a nightly available though, so i'm going to try it
thanks :)
