### ISSUE TITLE
Add federated wiki?

### ISSUE THREAD

**Issue by alanz** [bashrc/freedombone#69]
As per http://ward.fed.wiki.org/ and https://github.com/fedwiki/wiki

**Comment by bashrc** [comment]
Curious, but I'm not sure I really have grokked the concept. Does this mean there are individual federated hosts but they edit what in effect is a global wiki?

**Comment by alanz** [comment]
Yes.  But it operates somewhat like the W3C annotations, in that site A can modify something on site B, but the modification lives on site A. It is up to the site B owner to decide to bring the change over or not.

The default local install is read-only, but you can still interact with it from your browser because it stores all the changes in browser local storage. At some later stage you can sync these changes with a remote one.

See http://video.fed.wiki.org/view/welcome-visitors/view/federated-wiki-videos for some more overview.

**Comment by herbsmn** [comment]
earlier this year I tested whether or not federated wiki worked on a tor onion service, and it did! https://github.com/fedwiki/wiki/issues/71#issuecomment-275547359 the site is down now though.

**Comment by bashrc** [comment]
Exists in release 3.1
