### ISSUE TITLE
Failed install on rPi dealing with tox

### ISSUE THREAD

**Issue by nextlevelkid** [bashrc/freedombone#70]
Greetings,  Ever since i found your work, ive been so intrigued with your code. 
I am working with a community in a very rural area to create an emergency backbone comm sys for the town using existing fiber for internets backbone, local weather mesh repeater system and also developing offline decentralized comm structure for the people to stay connected. working to use Hamm,  RF Wireless and Wifi to connect the dots. 
Of course simply starting w wifi and mesh. 
 In this process of getting the mesh on the rpi, ive been dealing with some issues. Love some feedback on this as i am new to aspects of this. 

Anyways, kept running into issues with toxid and toxcore when installing on rpi. i found that by running freedombone-mesh to install on local pi, it was failing with errors saying tox/toxav.h isnt a current directory which would stop the install. 
So i saw that tox was put inside /includes/ folder and so then proceeded to copy over the toxav.h from toxcore and the install completed properly. 

So im not sure i did the correct thing because this is my first run at doing this. 
Anyways, love to know a bit more about the system. hopefully this isnt a bug and its more my learning curve. but if it is a bug hopefully this was helpful. 

Thanks so much for your creative works. this is the best ive found by far. Love how you see the world digitally and the tools you have so graciously been developing..  A HUGE THANK YOU!!!

All the best. 
Shan

**Comment by bashrc** [comment]
Installing on a rPi would be difficult because it's not supported by the image builder. The most likely explanation is that toxcore didn't install properly or it wasn't installed from the expected repo/commit. That's contained within freedombone-app-tox

**Comment by nextlevelkid** [comment]
Ok thank you i will explore this more.. I got it working, then tried another time and it failed again... 
Yes it seems its having issues w pi. 
 thanks for tip with the freedombone-app-tox, ill see if that resolves that error.  thank you kindly~!
