### ISSUE TITLE
Website: More details about connectivity.

### ISSUE THREAD

**Issue by y-nort** [bashrc/freedombone#71]
Tor seems to be (optionally?) integrated into freedombone. But I think there are not enough details about it on the website, aside from onion domains being created, to know what to expect.
Some of the questions I was left with:

"--onion yes":  Is this just about onion vs regular domains being set up? Or is the whole server being preconfigured/secured to restrict access to "only via onion addresses"?

What about outgoing connections? Is everything routed through Tor, or will the server and the apps make regular clearnet connections?
Is freedombone using Google DNS Servers (default in Debian)?

**Comment by bashrc** [comment]
At present the onion builds mean that sites are only available via their onion addresses and that you don't need to be concerned with certificates. It doesn't mean that everything gets routed through Tor.

I'll try to make this clearer, and also I could change that option to --onion-addresses-only to make it more obvious.

**Comment by bashrc** [comment]
On the DNS question the default DNS is Digital Courage, based in Germany. It's possible to change that to other DNS providers. https://en.wikipedia.org/wiki/Digitalcourage

**Comment by y-nort** [comment]
I'd say the situation is well explained. (thnx)

Maybe add just one sentence about:
Is it possible to set up a regular domain in an onion build? Onion addresses in a standard build? Have both at the same time?
Because I think, using "--onion" or "--onion-addresses-only" depends on the answers. (I would not expect to be able to set up regular domains in a build described as "onion addresses only")

**Comment by bashrc** [comment]
Yes that's how it works. You could add a clearnet domain to an onion build, but you'd have to do it by manually editing the nginx config.
