### ISSUE TITLE
Hello again

### ISSUE THREAD

**Issue by PiPc2** [bashrc/freedombone#80]
Convinced maintainer today to add a stretch image (https://dl.armbian.com/orangepipc2/)

Everything works fine when installing but I get a 502 Bad Gateway on nginx when I visit the Searx onion site.

Still remember this error from last time, but forgot solution (passwords are off)

**Comment by bashrc** [comment]
I think it just takes a while for the onion address to take effect. You can also check to see if the daemon is running with:

`systemctl status searx`

**Comment by PiPc2** [comment]
When I enable passwords, login screen shows but when I enter details it gives same 502 Bad Gateway error, disabling passwords doesn't help.

~$ systemctl status searx
● searx.service - Searx (search engine)
   Loaded: loaded (/etc/systemd/system/searx.service; enabled; vendor preset: en
   Active: active (running) since Sat 2017-12-16 20:30:07 UTC; 2s ago
 Main PID: 12672 (python)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/searx.service
           └─12672 /usr/bin/python /etc/searx/searx/webapp.py

Dec 16 20:30:07 freedombone.local systemd[1]: Started Searx (search engine).

**Comment by PiPc2** [comment]
Don't think its time related because I generated a few hours ago

**Comment by bashrc** [comment]
Active status suggests that the daemon is running, and because it's on an onion address you shouldn't need to have ports forwarded. what does /etc/nginx/sites-available/searx look like?

**Comment by PiPc2** [comment]
I forwarded port 443 and 80 because I also like to run a tor relay (middle)

server {
    listen 127.0.0.1:8094 default_server;
    root /etc/searx;
    server_name ghctkj54tizrndy2.onion;
    access_log /dev/null;
    error_log /var/log/searx_error.log warn;

    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    add_header Strict-Transport-Security max-age=0;

    location / {
    client_max_body_size 1M;
    client_body_buffer_size 128k;

    limit_conn conn_limit_per_ip 10;
    limit_req zone=req_limit_per_ip burst=10 nodelay;

        proxy_pass http://localhost:8888;
        #auth_basic "Search engine login";
        #auth_basic_user_file /etc/nginx/.htpasswd;
    }

    fastcgi_buffers 64 4K;

    error_page 403 /core/templates/403.php;
    error_page 404 /core/templates/404.php;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log /dev/null;
    }
}

**Comment by bashrc** [comment]
That looks ok, and I just tried reinstalling the searx app on my server and it works as expected. My guess is that this might be related to your tor setup if you're also running a relay.

**Comment by PiPc2** [comment]
I'm not running a relay just yet, because freedombone services must be working first.
dokuwiki works fine, but Searx is my priority because Google is increasingly blocking public Searx instances. I'm installing more apps to see what is working.

Domains
=======

Name                      ICANN                     Tor                       
--------------------------------------------------------------------------
ssh                       freedombone.local         x2gw4q6kxu3yifhi.onion
Email                     freedombone.local         3tobncusjvgodbth.onion
dokuwiki                  -                         uy3t3xbt5txdg5fc.onion
searx                     -                         ghctkj54tizrndy2.onion

**Comment by bashrc** [comment]
Your dokuwiki looks ok, so nginx and tor is working. Maybe this is latency thing with something timing out. Or it could be related to RAM.

**Comment by bashrc** [comment]
Enable logging from the administrator control panel and then see what gets generated for searx when you visit it.

**Comment by PiPc2** [comment]
Enabled logging but having some trouble finding the right logs, is it /var/log/searx_error.log? because that one shows this: 

2017/12/16 21:30:06 [warn] 28190#28190: *59 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: ghctkj54tizrndy$
$ctkj54tizrndy2.onion, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8888/", host: "ghctkj54tizrndy2.onion"
 
or in syslog/damonlog

Dec 16 21:57:51 freedombone systemd[1]: Stopped Searx (search engine).
Dec 16 21:57:51 freedombone systemd[1]: Started Searx (search engine).
Dec 16 21:57:53 freedombone python[17300]: Traceback (most recent call last):
Dec 16 21:57:53 freedombone python[17300]:   File "/etc/searx/searx/webapp.py", line 65, in <module>
Dec 16 21:57:53 freedombone python[17300]:     from searx.search import SearchWithPlugins, get_search_query_from_webapp
Dec 16 21:57:53 freedombone python[17300]:   File "/etc/searx/searx/search.py", line 34, in <module>
Dec 16 21:57:53 freedombone python[17300]:     from searx.plugins import plugins
Dec 16 21:57:53 freedombone python[17300]:   File "/etc/searx/searx/plugins/__init__.py", line 25, in <module>
Dec 16 21:57:53 freedombone python[17300]:     from searx.plugins import (oa_doi_rewrite,
Dec 16 21:57:53 freedombone python[17300]:   File "/etc/searx/searx/plugins/oa_doi_rewrite.py", line 14, in <module>
Dec 16 21:57:53 freedombone python[17300]:     doi_resolvers = settings['doi_resolvers']
Dec 16 21:57:53 freedombone python[17300]: KeyError: 'doi_resolvers'
Dec 16 21:57:54 freedombone systemd[1]: searx.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 21:57:54 freedombone systemd[1]: searx.service: Unit entered failed state.
Dec 16 21:57:54 freedombone systemd[1]: searx.service: Failed with result 'exit-code'.
Dec 16 21:57:54 freedombone systemd[1]: searx.service: Service hold-off time over, scheduling restart.
Dec 16 21:57:54 freedombone systemd[1]: Stopped Searx (search engine).
Dec 16 21:57:54 freedombone systemd[1]: Started Searx (search engine).

**Comment by bashrc** [comment]
You could try adding the doi_resolvers section as seen at the end of https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L741 to /etc/searx/searx/settings.yml, then restarting the daemon.

I'm not sure what that does, but the KeyError above means that might be the problem.

**Comment by PiPc2** [comment]
Well that worked, got a new log:

Dec 16 23:00:57 freedombone systemd[1]: searx.service: Service hold-off time over, scheduling restart.
Dec 16 23:00:57 freedombone systemd[1]: Stopped Searx (search engine).
Dec 16 23:00:57 freedombone systemd[1]: Started Searx (search engine).
Dec 16 23:00:59 freedombone python[25658]: Traceback (most recent call last):
Dec 16 23:00:59 freedombone python[25658]:   File "/etc/searx/searx/webapp.py", line 33, in <module>
Dec 16 23:00:59 freedombone python[25658]:     from searx import logger
Dec 16 23:00:59 freedombone python[25658]:   File "/etc/searx/searx/__init__.py", line 54, in <module>
Dec 16 23:00:59 freedombone python[25658]:     settings = load(settings_yaml)
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
Dec 16 23:00:59 freedombone python[25658]:     return loader.get_single_data()
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
Dec 16 23:00:59 freedombone python[25658]:     node = self.get_single_node()
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
Dec 16 23:00:59 freedombone python[25658]:     document = self.compose_document()
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
Dec 16 23:00:59 freedombone python[25658]:     node = self.compose_node(None, None)
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
Dec 16 23:00:59 freedombone python[25658]:     node = self.compose_mapping_node(anchor)
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
Dec 16 23:00:59 freedombone python[25658]:     while not self.check_event(MappingEndEvent):
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
Dec 16 23:00:59 freedombone python[25658]:     self.current_event = self.state()
Dec 16 23:00:59 freedombone python[25658]:   File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
Dec 16 23:00:59 freedombone python[25658]:     "expected <block end>, but found %r" % token.id, token.start_mark)
Dec 16 23:00:59 freedombone python[25658]: yaml.parser.ParserError: while parsing a block mapping
Dec 16 23:00:59 freedombone python[25658]:   in "/etc/searx/searx/settings.yml", line 1, column 1
Dec 16 23:00:59 freedombone python[25658]: expected <block end>, but found '<scalar>'
Dec 16 23:00:59 freedombone python[25658]:   in "/etc/searx/searx/settings.yml", line 523, column 35
Dec 16 23:00:59 freedombone systemd[1]: searx.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 23:00:59 freedombone systemd[1]: searx.service: Unit entered failed state.
Dec 16 23:00:59 freedombone systemd[1]: searx.service: Failed with result 'exit-code'.

**Comment by bashrc** [comment]
Looks like there might still be an error in settings.yml: expected , but found ''

**Comment by PiPc2** [comment]
Started from 0 again because other apps began interfering with Searx.

Got this error: 
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Dec 17 18:06:19 freedombone python[10180]: [2017-12-17 18:06:19,830] ERROR in app: Exception on / [GET]
Dec 17 18:06:19 freedombone python[10180]: Traceback (most recent call last):
Dec 17 18:06:19 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Dec 17 18:06:19 freedombone python[10180]:     response = self.full_dispatch_request()
Dec 17 18:06:19 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Dec 17 18:06:19 freedombone python[10180]:     rv = self.handle_user_exception(e)
Dec 17 18:06:19 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Dec 17 18:06:19 freedombone python[10180]:     reraise(exc_type, exc_value, tb)
Dec 17 18:06:19 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1610, in full_dispatch_request
Dec 17 18:06:19 freedombone python[10180]:     rv = self.preprocess_request()
Dec 17 18:06:19 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1831, in preprocess_request
Dec 17 18:06:19 freedombone python[10180]:     rv = func()
Dec 17 18:06:19 freedombone python[10180]:   File "/etc/searx/searx/webapp.py", line 399, in pre_request
Dec 17 18:06:19 freedombone python[10180]:     preferences = Preferences(themes, list(categories.keys()), engines, plugins)
Dec 17 18:06:19 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 250, in __init__
Dec 17 18:06:19 freedombone python[10180]:     choices=LANGUAGE_CODES),
Dec 17 18:06:19 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 37, in __init__
Dec 17 18:06:19 freedombone python[10180]:     self._post_init()
Dec 17 18:06:19 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 67, in _post_init
Dec 17 18:06:19 freedombone python[10180]:     self._validate_selection(self.value)
Dec 17 18:06:19 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 62, in _validate_selection
Dec 17 18:06:19 freedombone python[10180]:     raise ValidationException('Invalid value: "{0}"'.format(selection))
Dec 17 18:06:19 freedombone python[10180]: ValidationException: Invalid value: "all"
Dec 17 18:06:50 freedombone python[10180]: [2017-12-17 18:06:50,813] ERROR in app: Exception on / [GET]
Dec 17 18:06:50 freedombone python[10180]: Traceback (most recent call last):
Dec 17 18:06:50 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Dec 17 18:06:50 freedombone python[10180]:     response = self.full_dispatch_request()
Dec 17 18:06:50 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Dec 17 18:06:50 freedombone python[10180]:     rv = self.handle_user_exception(e)
Dec 17 18:06:50 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Dec 17 18:06:50 freedombone python[10180]:     reraise(exc_type, exc_value, tb)
Dec 17 18:06:50 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1610, in full_dispatch_request
Dec 17 18:06:50 freedombone python[10180]:     rv = self.preprocess_request()
Dec 17 18:06:50 freedombone python[10180]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1831, in preprocess_request
Dec 17 18:06:50 freedombone python[10180]:     rv = func()
Dec 17 18:06:50 freedombone python[10180]:   File "/etc/searx/searx/webapp.py", line 399, in pre_request
Dec 17 18:06:50 freedombone python[10180]:     preferences = Preferences(themes, list(categories.keys()), engines, plugins)
Dec 17 18:06:50 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 250, in __init__
Dec 17 18:06:50 freedombone python[10180]:     choices=LANGUAGE_CODES),
Dec 17 18:06:50 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 37, in __init__
Dec 17 18:06:50 freedombone python[10180]:     self._post_init()
Dec 17 18:06:50 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 67, in _post_init
Dec 17 18:06:50 freedombone python[10180]:     self._validate_selection(self.value)
Dec 17 18:06:50 freedombone python[10180]:   File "/etc/searx/searx/preferences.py", line 62, in _validate_selection
Dec 17 18:06:50 freedombone python[10180]:     raise ValidationException('Invalid value: "{0}"'.format(selection))
Dec 17 18:06:50 freedombone python[10180]: ValidationException: Invalid value: "all"
