### ISSUE TITLE
Searx issue

### ISSUE THREAD

**Issue by PiPc2** [bashrc/freedombone#83]
Dec 23 14:18:57 freedombone python[6781]: [2017-12-23 14:18:57,472] ERROR in app: Exception on / [GET]
Dec 23 14:18:57 freedombone python[6781]: Traceback (most recent call last):
Dec 23 14:18:57 freedombone python[6781]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Dec 23 14:18:57 freedombone python[6781]:     response = self.full_dispatch_request()
Dec 23 14:18:57 freedombone python[6781]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Dec 23 14:18:57 freedombone python[6781]:     rv = self.handle_user_exception(e)
Dec 23 14:18:57 freedombone python[6781]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Dec 23 14:18:57 freedombone python[6781]:     reraise(exc_type, exc_value, tb)
Dec 23 14:18:57 freedombone python[6781]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1610, in full_dispatch_request
Dec 23 14:18:57 freedombone python[6781]:     rv = self.preprocess_request()
Dec 23 14:18:57 freedombone python[6781]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1831, in preprocess_request
Dec 23 14:18:57 freedombone python[6781]:     rv = func()
Dec 23 14:18:57 freedombone python[6781]:   File "/etc/searx/searx/webapp.py", line 399, in pre_request
Dec 23 14:18:57 freedombone python[6781]:     preferences = Preferences(themes, list(categories.keys()), engines, plugins)
Dec 23 14:18:57 freedombone python[6781]:   File "/etc/searx/searx/preferences.py", line 250, in __init__
Dec 23 14:18:57 freedombone python[6781]:     choices=LANGUAGE_CODES),
Dec 23 14:18:57 freedombone python[6781]:   File "/etc/searx/searx/preferences.py", line 37, in __init__
Dec 23 14:18:57 freedombone python[6781]:     self._post_init()
Dec 23 14:18:57 freedombone python[6781]:   File "/etc/searx/searx/preferences.py", line 67, in _post_init
Dec 23 14:18:57 freedombone python[6781]:     self._validate_selection(self.value)
Dec 23 14:18:57 freedombone python[6781]:   File "/etc/searx/searx/preferences.py", line 62, in _validate_selection
Dec 23 14:18:57 freedombone python[6781]:     raise ValidationException('Invalid value: "{0}"'.format(selection))
Dec 23 14:18:57 freedombone python[6781]: ValidationException: Invalid value: "all"

**Comment by bashrc** [comment]
What architecture are you running on? Is it arm?

**Comment by PiPc2** [comment]
Arm64
