### ISSUE TITLE
Building the homeserver image on Debian 9 Stretch

### ISSUE THREAD

**Issue by Falgn0n** [bashrc/freedombone#84]
Working on my Debian 9 system, trying to build the homeserver image:

Command:
`freedombone-image -t i386`

Error: 
```
ERROR: command failed: ['install-mbr', 'build/freedombone-min-2017-12-24_all-i386.img']

install-mbr:build/freedombone-min-2017-12-24_all-i386.img: Probable detection of modern MBR format which is currently incompatible with install-mbr.  Installing will probably break Windows installations on this system.  Use --force to override.

Makefile:179: recipe for target 'i386' failed
make: *** [i386] Error 1
Build failed
```

(Not sure what to edit or where to add the `--force` to override ... ?)

**Comment by bashrc** [comment]
It looks like I need more testing on debian. Probably the changes I made to vmdebootstrap need to be installed on debian systems within freedombone-image/image_setup

**Comment by bashrc** [comment]
Until I get around to fixing this I've created a pre-built i386 image, which is available at https://freedombone.net/downloads/current

**Comment by bashrc** [comment]
This should now be fixed. It looks like the --force option was enough.

**Comment by Falgn0n** [comment]
Nice. So far the image build is going smooth.
(maybe solved?)

Unrelated:
- Will running `freedombone-image -t amd64`  work (for a 64bit image)?

**Comment by bashrc** [comment]
Yes, it should.

**Comment by Falgn0n** [comment]
original issue solved  - closing this

(also - thanks!)
