### ISSUE TITLE
Can we get a #peertube seedbox

### ISSUE THREAD

**Issue by Openmedianetwork** [bashrc/freedombone#85]
Can we get a seedbox for peertube https://github.com/Openmedianetwork/visionOntv/issues/1

**Comment by bashrc** [comment]
I'm currently updating to the new LTS version of Node and so it will be possible to install a recent version of peertube, rather than the early alpha which currently exists. I know there are a lot of useful features planned for peertube, such as mirroring and blocking controls.

**Comment by bashrc** [comment]
As of release 3.1 last week, the latest PeerTube is now supported.
