### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by PiPc2** [bashrc/freedombone#87]
Same error as before.

[2018-04-20 09:21:25,864] ERROR in app: Exception on / [GET]
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]: Traceback (most recent call last):
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line $
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     response = self.full_dispatch_request()
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line $
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     rv = self.handle_user_exception(e)
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line $
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     reraise(exc_type, exc_value, tb)
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line $
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     rv = self.preprocess_request()
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line $
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     rv = func()
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/etc/searx/searx/webapp.py", line 404, in pre_request
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     preferences = Preferences(themes, list(categories.keys()), engi$
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/etc/searx/searx/preferences.py", line 246, in __init__
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     choices=LANGUAGE_CODES),
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/etc/searx/searx/preferences.py", line 37, in __init__
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     self._post_init()
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/etc/searx/searx/preferences.py", line 67, in _post_init
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     self._validate_selection(self.value)
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:   File "/etc/searx/searx/preferences.py", line 62, in _validate_sel$
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]:     raise ValidationException('Invalid value: "{0}"'.format(selecti$
Apr 20 09:21:25 osilv76cbezmboxk3wx5glyd3fmmbdd7o64bhxbeplyvb7ia57plvfqd python[823]: ValidationException: Invalid value: "all"

Also, could switch to onion v2 addresses by default because most people don't run alpha versions and gogs doesn't seem to switch to v2 addresses when I enable USE_V2_ONION_ADDRESS=1 in src/freedombone-utils-onion

thanks.

**Comment by PiPc2** [comment]
Both on AMD64 and ARM64

**Comment by bashrc** [comment]
What app is this?

**Comment by bashrc** [comment]
I've not managed to reproduce this yet, and it might have something to do with selecting certain search engines. Within the searx preferences did you allow any other search engines, and if so which ones?

**Comment by PiPc2** [comment]
Didn't choose anything, only added 1 to USE_V2_ONION_ADDRESS in src/freedombone-utils-onion while installing freedombone, added searx as only app, enabled the logs,  visited the generated onion address and got the Internal Server Error.

**Comment by PiPc2** [comment]
had to change language from "all" to "en"
