### ISSUE TITLE
add way to change Dynamic DNS settings

### ISSUE THREAD

**Issue by jeroen7s** [bashrc/freedombone#91]
when setting up dns it asked me for 4 fields, i only filled in the first one and continued, but now i don't know how to change it again, is there an option to change it?
also what do i need to fill in in the "code" field, and the last two fields, that was not clear to me so that's why i left it empty

**Comment by bashrc** [comment]
If you're not using freeDNS the code field won't be relevant

**Comment by jeroen7s** [comment]
Well i am using freedns now, but haven't put in the code (don't know where to find it?)

**Comment by jeroen7s** [comment]
Ah i think i've found the code now (api key? ) but idk where to set it since i'm past the setup alreaddy

**Comment by jeroen7s** [comment]
Also install wizard said the code was wrong, but then continued anyway without allowing me to change the code

**Comment by bashrc** [comment]
When you add a domain if you go to the dynamic dns settings there is a quick cron link with the code at the bottom

**Comment by bashrc** [comment]
The point about being able to change dynamic dns settings after install is a good one. I'll add that.

**Comment by bashrc** [comment]
Added and also upgraded inadyn to the latest version.

**Comment by jeroen7s** [comment]
cool, thanks a lot :)
